### ISSUE TITLE
Failed to load mod

### ISSUE THREAD

**Issue by Protheus** [JohnTheCoolingFan/RandomFactorioThings#1]
Upon loading of the latets v0.14.0, I get the below error.
Loading of v0.13.2 works fine.

![capture3](https://user-images.githubusercontent.com/1455178/47059301-1a058080-d1c9-11e8-9eab-cabb7805e172.JPG)

Using the latest Beta 0.16 of factorio

**Comment by Protheus** [comment]
Issue still applicable in 0.14.3

**Comment by JohnTheCoolingFan** [comment]
Do you use any other mods? Please send me your mods list.
