### ISSUE TITLE
Loaders mods support

### ISSUE THREAD

**Issue by CaveJohnson376** [JohnTheCoolingFan/RandomFactorioThings#15]
This mod needs to support mods like "Vanilla loaders HD", "Miniloaders" and so on. Or i can ask these mods authors to do so. Or, maybe, i can try to do that myself...

**Comment by JohnTheCoolingFan** [comment]
RFT already supports [Deadlock's loaders](https://mods.factorio.com/mod/deadlock-beltboxes-loaders). Vanilla loaders HD has support for other mods, you can simply call a function and make a new loader. Miniliader doesn't have this ability.
I'll make loader for VLHD. For Miniloader, go to [its repo](https://github.com/mspielberg/factorio-miniloader) and ask for RFT support...

**Comment by JohnTheCoolingFan** [comment]
Vanilla loaders hd has a bug in its code. https://github.com/kirazy/vanilla-loaders-hd/issues/2

**Comment by CaveJohnson376** [comment]
Waiting for https://github.com/mspielberg/factorio-miniloader/pull/41 merge

**Comment by JohnTheCoolingFan** [comment]
Vanilla Loaders HD and Miniloaders are done
What next?

**Comment by CaveJohnson376** [comment]
It is done for now, i think :)
