### ISSUE TITLE
Plutonium and nuclear splitters visuals are kinda broken

### ISSUE THREAD

**Issue by CaveJohnson376** [JohnTheCoolingFan/RandomFactorioThings#21]
![GIF](https://user-images.githubusercontent.com/33164023/79614729-92c8fe00-811a-11ea-86bb-01b85f388e62.gif)

**Comment by JohnTheCoolingFan** [comment]
*ah crap*

**Comment by JohnTheCoolingFan** [comment]
Is it hr or lr graphics?

**Comment by CaveJohnson376** [comment]
lr

**Comment by JohnTheCoolingFan** [comment]
ok thx

**Comment by JohnTheCoolingFan** [comment]
Is everything ok in hr?

**Comment by CaveJohnson376** [comment]
i dunno, can't play with hr because laptop is shit

**Comment by CaveJohnson376** [comment]
upper part of (pluto-/ura-)nium splitter has express splitter texture, lower section has bugged texture, up/down splitters seems to be fine
![image](https://user-images.githubusercontent.com/33164023/79615824-04a24700-811d-11ea-8cd0-d8dcde4ab483.png)
*added express splitter for comparison*

**Comment by JohnTheCoolingFan** [comment]
I understand what causes this issue...
I think the easiest way to fix this will be to completely remake sprites again. Guess this won't happen in a long time...

**Comment by CaveJohnson376** [comment]
ok then, waiting for update... or it's better to do some expirementing with PE?
