### ISSUE TITLE
Missing require() for module-technology tree

### ISSUE THREAD

**Issue by AlienXAXS** [JohnTheCoolingFan/RandomFactorioThings#3]
Hiya,
Love the mod - just was a bit disappointed to see that the mixed modules are not working :(

Looks like you're missing the require line for the modules lua file inside data.lua:
`require("prototypes.technology.module-technology")`

**Comment by JohnTheCoolingFan** [comment]
Thanks for a report!
This issue was fixed in 0.14.7

Also I use the system that in data.lua I require() only main files (except categories) and in main files I require() all other files.
